version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: image_processing
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_db
    ports:
      - "6379:6379"  # Expose Redis on port 6379
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    driver: local

  redis_data:
    driver: local
