services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: image_processing
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # nodejs_app:
  #   build: 
  #     context: .  # Assuming Dockerfile is in the root of your project
  #     dockerfile: Dockerfile
  #   container_name: nodejs_app
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: image_processing
  #     REDIS_HOST: redis_db
  #     REDIS_PORT: 6379
  #   ports:
  #     - "8000:8000" # Expose your app on port 8000
  #   depends_on:
  #     - postgres
  #     - redis
  #   volumes:
  #     - .:/usr/src/app
  #   command: npm run dev # Adjust this according to how you start your Node.js app

volumes:
  postgres_data:
    driver: local

  redis_data:
    driver: local
